# Generated by Django 5.0.4 on 2024-05-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0006_alter_user_email_alter_user_uid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "type",
                    models.CharField(
                        choices=[("dm", "Direct Message"), ("gc", "Group Chat")],
                        max_length=2,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("last_message_time", models.DateTimeField(auto_now=True)),
                (
                    "document_id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                (
                    "participants",
                    models.ManyToManyField(related_name="chats", to="user.user"),
                ),
            ],
        ),
    ]
