# Generated by Django 5.0.4 on 2024-05-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
