# Generated by Django 5.0.4 on 2024-05-16 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="channel_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
