# Generated by Django 5.0.4 on 2024-05-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_session_channel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="community",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="community/"),
        ),
    ]
