# Generated by Django 5.0.4 on 2024-05-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0006_rename_date_session_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="duration",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
