# Generated by Django 5.0.4 on 2024-05-23 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0007_session_duration"),
        ("user", "0006_alter_user_email_alter_user_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="user.user",
            ),
        ),
    ]
