# Generated by Django 5.0.4 on 2024-05-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0008_alter_membership_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
