# Generated by Django 5.0.4 on 2024-05-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0009_alter_session_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="session",
            name="time",
            field=models.DateTimeField(),
        ),
    ]
