# Generated by Django 5.0.4 on 2024-05-30 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0010_alter_session_description_alter_session_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="community.session",
            ),
        ),
    ]
