# Generated by Django 5.0.4 on 2024-05-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "firebase_uid",
                    models.CharField(
                        max_length=128, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
            ],
        ),
    ]
