# Generated by Django 5.0.4 on 2024-05-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
