# Generated by Django 5.0.4 on 2024-05-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_rename_profile_pic_user_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="uid",
            field=models.CharField(
                max_length=128, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
