# Generated by Django 5.0.4 on 2024-05-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community_post", "0002_comment_vote_commentvote_savedpost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentvote",
            old_name="vote",
            new_name="value",
        ),
    ]
