# Generated by Django 5.0.4 on 2024-05-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community_post", "0003_rename_vote_commentvote_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitypost",
            name="title",
            field=models.CharField(default="Default Title", max_length=255),
            preserve_default=False,
        ),
    ]
